---
title: "DataFest_2022"
author: "DataFest_2022"
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
library(reshape2)
library(extrafont)
library(ggchicklet)


theme_set(theme_bw())
```

```{r}
# Read the data

player1 <- read.csv("Data/player-6607011.csv")

player2 <- read.csv("Data/player-6486029.csv")

drug_test <- read.csv("Data/S5_scores_cleaned.csv")

wholeData <- read.csv("Data/logs.csv")
```

```{r}
wholeData <- filter(wholeData,
                    player_id %in% drug_test$player_id)



wholeData %>% 
  group_by(player_id) %>% 
  mutate(weeks = week(ymd(date)) - week(ymd(min(date)))) %>% 
  filter(weeks %in% drug_test$weeks) %>% 
  filter(!is.na(total_points)) %>% 
  select(weeks, total_points)


wholeData %>% 
  group_by(player_id) %>% 
  mutate(weeks = week(ymd(date)) - week(ymd(min(date)))) %>% 
  filter(weeks %in% drug_test$weeks) %>% 
  filter(!is.na(player_points)) %>% 
  ggplot() +
  geom_boxplot(aes(x = as.character(weeks),
                   y = player_points))
```

```{r}
drug_test_new <- drug_test %>% 
  na.omit() %>%
  filter(player_id %in% wholeData$player_id) %>% 
  mutate(pre_value = lag(S5_mean)) %>% 
  group_by(player_id) %>% 
  mutate(changed_score = ifelse(weeks == 0, 0, S5_mean - pre_value)) %>% 
  mutate(Status = ifelse(changed_score > 0, "increase", ifelse(changed_score < 0, "decrease", "unchanged"))) %>%
  select(-pre_value) %>% 
  ungroup()
```

```{r}
alpha1 = 1
alpha2 = 1

color_set1 <- c(rgb(246/255, 206/255, 75/255, alpha1), rgb(65/255, 165/255, 146/255, alpha1), rgb(25/255, 152/255, 211/255, alpha1))
color_set2 <- c(rgb(1/255, 200/255, 238/255, alpha1), rgb(228/255, 19/255, 118/255, alpha1), rgb(16/255, 27/255, 55/255, alpha1))
color_set3 <- c(rgb(211/255, 66/255, 45/255, alpha1), rgb(199/255, 209/255, 213/255, alpha1), rgb(107/255, 185/255, 207/255, alpha1))
color_set4 <- c(rgb(137/255, 217/255, 157/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1))


pos1 <- c(0.582, 0.795, 1.05, 0.582, 0.816, 1.05, 0.517, 0.806, 1.05, 0.569, 0.754, 1.05)
pos2 <- c(0.482, 0.695, 0.95, 0.482, 0.716, 0.95, 0.417, 0.706, 0.95, 0.469, 0.654, 0.95)

color_text1 <- c(rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1))
color_text2 <- c(rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(30/255, 89/255, 89/255, alpha1), rgb(59/255, 140/255, 110/255, alpha1))
color_text3 <- c(rgb(222/255, 239/255, 231/255, alpha2))
```

```{r}
drug_test_new %>% 
  group_by(weeks, Status) %>% 
  mutate(value = 1) %>% 
  summarise(sum_value = sum(value)) %>% 
  ungroup() %>% 
  group_by(weeks) %>% 
  mutate(prop = sum_value / sum(sum_value)) %>% 
  ungroup() %>% 
  filter(weeks != 0) %>% 
  ggplot(aes(x = factor(as.character(weeks), level = c("3", "6", "12", "24")),
             y = prop,
             fill = Status)) +
  geom_col() +
  scale_fill_manual(values = color_set4) +
  annotate("text", 
           x = c(1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4),
           y = pos2,
           label = c("0.532", "0.213", "0.255", "0.532", "0.234", "0.234", "0.467", "0.289", "0.244", "0.519", "0.185", "0.296"),
           color = color_text2,
           fontface = "bold",
           size = 5,
           family = "mono",
           lineheight = .5) +
  theme(
    title = element_text(
      face = "plain",
      size = 12,
      family = "mono"
    ),
    legend.title = element_text(
      colour = "black",
      face = "plain",
      size = 14,
      family = "mono"
    ),
    legend.text = element_text(
      colour = "black",
      face = "plain",
      size = 12,
      family = "mono"
    ),
    axis.text.x = element_text(size = 12, face = "plain", family = "mono"),
    axis.text.y = element_text(size = 12, face = "plain", family = "mono"),
    axis.title.x = element_text(size = 12, face = "plain", family = "mono"),
    axis.title.y = element_text(size = 12, face = "plain", family = "mono"),
    legend.position = "right",
    panel.grid.major = element_blank()
  ) +
  labs(y = "Proportion of Each Status",
       x = "Number of Weeks")

ggsave("a.png")
```

```{r}
wholeData %>% 
  group_by(player_id) %>% 
  mutate(weeks = (as.numeric(as.Date(date)) - as.numeric(as.Date(min(date))))) %>% 
  filter(weeks %in% drug_test$weeks) %>%
  filter(!is.na(player_points)) %>%
  ungroup() %>% 
  group_by(weeks) %>% 
  mutate(sum = n(),
         mean = mean(player_points),
         max = max(player_points),
         min = IQR(player_points)) %>% 
  select(weeks, player_points, sum) %>% 
  ggplot(aes(x = factor(as.character(weeks), level = c("0", "3", "6", "12", "24")),
                   y = player_points)) +
  geom_boxplot(fill = c("#89D99D", "#02A676", "#008C72", "#007369", "#005A5B"),
               outlier.shape = NA,
               width = 5) +
  theme(
    title = element_text(
      face = "plain",
      size = 12,
      family = "mono"
    ),
    legend.title = element_text(
      colour = "black",
      face = "plain",
      size = 14,
      family = "mono"
    ),
    legend.text = element_text(
      colour = "black",
      face = "plain",
      size = 12,
      family = "mono"
    ),
    axis.text.x = element_text(size = 12, face = "plain", family = "mono"),
    axis.text.y = element_text(size = 12, face = "plain", family = "mono"),
    axis.title.x = element_text(size = 12, face = "plain", family = "mono"),
    axis.title.y = element_text(size = 12, face = "plain", family = "mono"),
    legend.position = "none",
    panel.grid.major = element_blank()
  ) +
  labs(y = "Score Gained by Players",
       x = "Number of Weeks")


ggsave("b.png")
```

```{r}
color_bar <-  c(rgb(59/255, 140/255, 110/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1), rgb(137/255, 217/255, 157/255, alpha1))

wholeData %>% 
  group_by(player_id) %>% 
  mutate(weeks = (as.numeric(as.Date(date)) - as.numeric(as.Date(min(date))))) %>% 
  filter(weeks %in% drug_test$weeks) %>%
  filter(!is.na(player_points)) %>%
  ungroup() %>% 
  group_by(weeks) %>% 
  mutate(sum = n(),
         mean = mean(player_points),
         max = max(player_points),
         min = IQR(player_points)) %>% 
  select(weeks, player_points, sum, mean, max, min) %>% 
  arrange(weeks) %>% 
  mutate(q1 = ifelse(weeks == 0, 60,
                     ifelse(weeks == 3, 60,
                            ifelse(weeks == 6, 112.5,
                                   ifelse(weeks == 12, 30,
                                          ifelse(weeks == 24, 85))))),
         q2 = ifelse(weeks == 0, 105,
                     ifelse(weeks == 3, 127.5,
                            ifelse(weeks == 6, 150,
                                   ifelse(weeks == 12, 120,
                                          ifelse(weeks == 24, 150)))))) %>% 
  ggplot() +
  geom_errorbar(aes(x = factor(as.character(weeks), level = c("0", "3", "6", "12", "24")),
                    ymax = q2,
                    ymin = q1),
                # linetype = "longdash",
                  width = 0.2,
                  color = rgb(59/255, 140/255, 110/255, alpha1)) +
  geom_point(aes(x = factor(as.character(weeks), level = c("0", "3", "6", "12", "24")),
                 y = mean,
                 size = 10),
             color = rgb(59/255, 140/255, 110/255, alpha1),
             fill = rgb(137/255, 217/255, 157/255, alpha1))
```


